services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: movasseghi
      POSTGRES_PASSWORD: movasseghi
      POSTGRES_DB: movasseghi
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U movasseghi -d movasseghi']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
